### ISSUE TITLE
Suggestion: use the same environment vars as drone-cli

### ISSUE THREAD

**Issue by patrickjahns** [Dorian/drone-builds#1]
drone-cli uses `DRONE_SERVER` and `DRONE_TOKEN` environment vars - it is probably best to reuse the credentials for this command line tool to keep things strange (and don't require additional configuration) 

see: http://readme.drone.io/usage/getting-started-cli/

**Comment by Dorian** [comment]
I kept DRONE_DOMAIN and do protocol/domain "parsing" from `DRONE_SERVER` (defaulting to `http` for now).

https://github.com/Dorian/drone-builds/commit/cf623189106add9251291891db7fa3930a699086 and https://github.com/Dorian/home-dotenv/commit/67353de1da290b845252cd41d2b1b02deed48734

**Comment by Dorian** [comment]
Thanks for the report :)
