### ISSUE TITLE
Restart command doesn't work because of build number

### ISSUE THREAD

**Issue by salvatorecordiano** [Dorian/drone-builds#2]
Restart command doesn't work because it uses build id and not build number. They are not always the same.

When showing build list, it's better to add build number, because drone API needs it in order to kill and restart a build.

Thanks

**Comment by Dorian** [comment]
@salvatorecordiano I tried your version but I don't know the difference between build number and build id. In my case it's always the same, maybe you are talking about job ids?

**Comment by Dorian** [comment]
@salvatorecordiano Thanks, I added the author column (with some coloring) https://github.com/Dorian/drone-builds/commit/0071f500fc5011d5a25635d5a8b37450de873962

**Comment by salvatorecordiano** [comment]
@Dorian thanks. To restart a build via API you need to do the following POST

`POST /api/repos/{owner}/{name}/builds/{number}`

For more info you can check docs here http://readme.drone.io/api/build-endpoint/

So, it's better to display the build number field instead of build id. What do you think?

**Comment by Dorian** [comment]
@salvatorecordiano Still not sure when `id` would be different than `number`. Also I see `number` in `jobs` too (and jobs have an `id` too, that I call `job_id` (in my case there is only one job for each build so I didn't handle the `jod_id` parameter for now :D )

**Comment by salvatorecordiano** [comment]
@Dorian I tried to kill a build using the number you show (build id) but it isn't working; then i tried drone API using the build number shown in drone-ui and it works. So it's different, both in displaying the build list on drone-builds and in the endpoints to kill and restart a build.

**Comment by Dorian** [comment]
So, I talked with @salvatorecordiano and actually I should not show the build id (it's internal) but only the build number.

<img width="991" alt="screen shot 2017-05-25 at 18 53 10" src="https://cloud.githubusercontent.com/assets/129149/26477586/71e117a4-417b-11e7-9b3c-3a0c597e089f.png">
